name: ui_challenge
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  flutter_launcher_icons: ^0.7.2+1
  scoped_model: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/qlicue.jpg"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/a.jpeg
    - assets/img/avocado.png
    - assets/img/pic.jpg
    - assets/profile/asha.jpg
    - assets/profile/saida.jpeg
    - assets/profile/robbyn.jpg
    - assets/img/qlicue.jpg

    - assets/dotify/icons/dotify_icon@3x.png
    - assets/dotify/icons/dotify_icon.png
    - assets/dotify/icons/back_btn.png
    - assets/dotify/icons/email_icon.png
    - assets/dotify/icons/menu_btn.png
    - assets/dotify/icons/dob_icon.png
    - assets/dotify/icons/password_icon.png
    - assets/dotify/icons/username_icon.png
    - assets/dotify/icons/view_album_btn.png
    - assets/dotify/icons/search_btn.png
    - assets/dotify/icons/pause_btn.png
    - assets/dotify/icons/pop_mic_icon.png
    - assets/dotify/icons/radio_icon.png
    - assets/dotify/icons/music_library_icon.png
    - assets/dotify/icons/rock_fire_icon.png
    - assets/dotify/icons/music_info.png
    - assets/dotify/icons/dismiss_music.png
    - assets/dotify/icons/browse_icon.png
    - assets/dotify/icons/activity_icon.png

    - assets/dotify/icons/songs_btn.png
    - assets/dotify/icons/playlists_btn.png
    - assets/dotify/icons/album_btn.png
    - assets/dotify/icons/artists_btn.png
    - assets/dotify/icons/share_music_btn.png
    - assets/dotify/icons/heart_song_btn.png
    - assets/dotify/icons/play_artist_btn.png
    - assets/dotify/icons/more_info_btn.png
    - assets/dotify/icons/favorite_song_btn.png
    - assets/dotify/icons/play_btn.png
    - assets/dotify/icons/settings_btn.png
    - assets/dotify/icons/play_btn_pop_up.png
    - assets/dotify/icons/repeat_btn.png
    - assets/dotify/icons/shuffle_btn.png
    - assets/dotify/icons/rewind_btn.png
    - assets/dotify/icons/fastforward_btn.png
    - assets/dotify/icons/speaker.png

    - assets/dotify/img/background.png
    - assets/dotify/img/avatar.png
    - assets/dotify/img/album_cover.png
    - assets/dotify/img/cover_song.png
    - assets/dotify/img/playing_now_background.png
    - assets/dotify/img/menu_cover.png
    - assets/dotify/img/user_profile.png

    - assets/dotify/img/acoustic.png
    - assets/dotify/img/top_hits.png
    - assets/dotify/img/viral.png
    
    - assets/dotify/img/pop.png
    - assets/dotify/img/electronic.png
    - assets/dotify/img/rock.png

    - assets/dotify/img/1.png
    - assets/dotify/img/2.png
    - assets/dotify/img/3.png
    - assets/dotify/img/4.png
    - assets/dotify/img/5.png
    - assets/dotify/img/6.png
    - assets/dotify/img/7.png
    - assets/dotify/img/8.png
    

  fonts:
    - family: Anton
      fonts:
        - asset: assets/dotify/fonts/Anton-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/dotify/fonts/Roboto-Bold.ttf
        - asset: assets/dotify/fonts/Roboto-Regular.ttf
        - asset: assets/dotify/fonts/Roboto-light.ttf
          weight: 700

    - family: AbrilFatface
      fonts:
        - asset: assets/dotify/fonts/AbrilFatface-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
